'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { PageHelp } from '@/components/ui/PageHelp';

/* ─────────────────────────────────────────────────────────────────
 * Settings shell — header + left sidebar nav + content slot.
 *
 * Each sub-route renders its own content; the layout provides:
 *  - the page header (title + lede)
 *  - a left-sidebar nav listing every settings section
 *  - the content frame on the right
 *
 * Active state is driven by pathname. Mobile collapses the sidebar
 * into a horizontal scrollable segmented list.
 * ───────────────────────────────────────────────────────────────── */

const SECTIONS: Array<{ href: string; label: string; lede: string; helpBody: string; helpTips?: string[] }> = [
 {
  href: '/dashboard/settings/account',
  label: 'Account',
  lede: 'Your profile, password, and session.',
  helpBody: 'Personal account settings — your display name, email address, and password. Changes here apply only to your user account, not the workspace.',
  helpTips: ['Your name appears on outreach drafts generated by the AI.', 'Password changes take effect immediately and sign out other sessions.'],
 },
 {
  href: '/dashboard/settings/workspace',
  label: 'Workspace',
  lede: 'The desk name, defaults, and preferences.',
  helpBody: 'Workspace-level settings shared by all members — name, notification preferences, and export defaults.',
  helpTips: ['Renaming the workspace updates it for all members.', 'These settings affect every search and campaign in this workspace.'],
 },
 {
  href: '/dashboard/settings/team',
  label: 'Team',
  lede: 'Members, roles, and invitations.',
  helpBody: 'View everyone who has access to this workspace. Invite new members by email to collaborate on searches and campaigns.',
  helpTips: ['Each member can run searches and view leads by default.', 'Admin members can manage billing and workspace settings.'],
 },
 {
  href: '/dashboard/settings/knowledge-base',
  label: 'Knowledge base',
  lede: 'House style — what the agent should know about your company.',
  helpBody: 'Custom knowledge the AI uses when writing emails or qualifying leads. Add your company overview, value proposition, and ideal customer profile.',
  helpTips: ['More specific context produces more targeted outreach.', 'The AI quotes this knowledge when generating email drafts.'],
 },
 {
  href: '/dashboard/settings/data-sources',
  label: 'Data sources',
  lede: 'Connected providers and their credentials.',
  helpBody: 'Configure which data sources the AI uses during prospecting — built-in sources, your own Apollo API key, and custom uploads.',
  helpTips: ['Enable or disable sources to control cost and data freshness.', 'View per-source usage and invocation counts.'],
 },
 {
  href: '/dashboard/settings/suppression',
  label: 'Suppression list',
  lede: 'Emails and domains the engine must never contact.',
  helpBody: 'Email addresses and domains that will never appear in search results or receive campaign emails. Use this for unsubscribers, competitors, and existing customers.',
  helpTips: ['Add full domains (e.g. competitor.com) to suppress all contacts there.', 'Suppressed contacts are filtered automatically from every search.'],
 },
 {
  href: '/dashboard/settings/api-keys',
  label: 'API keys',
  lede: 'Credentials for programmatic access.',
  helpBody: 'Generate API keys to access LeadreAI programmatically. Keys are shown once — copy and store them securely. Revoke any key at any time.',
  helpTips: ['Each key has a name to help you identify which service is using it.', 'Keys inherit the permissions of the workspace they belong to.'],
 },
 {
  href: '/dashboard/settings/billing',
  label: 'Billing & usage',
  lede: 'Plan, credits, and the ledger.',
  helpBody: 'Manage your subscription plan and credit balance. Monthly plan credits refill each billing cycle; top-up credits stack on top and never expire.',
  helpTips: ['One credit = one search job, regardless of lead count returned.', 'Top-ups are one-off purchases via Stripe or Paystack.'],
 },
 {
  href: '/dashboard/settings/email',
  label: 'Email & replies',
  lede: 'Sending account and inbound reply routing.',
  helpBody: 'Configure the email account used for outreach. Connect Gmail OAuth for branded sending, or set up custom SMTP, Resend, or SendGrid. Inbound webhooks route replies back to the campaign dashboard.',
  helpTips: ['Gmail OAuth is the simplest setup — no SMTP credentials required.', 'Inbound routing lets you see replies directly in each campaign.'],
 },
];

export default function SettingsLayout({ children }: { children: React.ReactNode }) {
 const pathname = usePathname();
 const isIndex = pathname === '/dashboard/settings';
 const active = SECTIONS.find((s) => pathname === s.href || pathname.startsWith(s.href + '/'));

 return (
  <div className="max-w-[1280px] mx-auto px-6 md:px-8 lg:px-10 py-8 md:py-10 animate-fade-up">
   {/* Inline header — same pattern as Dashboard / Leads / Tables */}
   <section className="mb-6 flex items-start justify-between gap-4 flex-wrap">
    <div>
     <h1 className="text-[22px] md:text-[26px] font-semibold tracking-[-0.01em] text-[color:var(--ink)]">
      {isIndex ? 'Settings' : (active?.label ?? 'Settings')}
     </h1>
     <p className="mt-0.5 text-[12.5px] text-[color:var(--ink-3)]">
      {isIndex
       ? 'Manage your workspace, team, integrations, and billing.'
       : (active?.lede ?? 'Manage your workspace.')}
     </p>
    </div>
    {active && (
     <PageHelp
      title={active.label}
      body={active.helpBody}
      tips={active.helpTips}
     />
    )}
    {isIndex && (
     <PageHelp
      title="Settings"
      body="Central settings hub. Navigate to account, billing, team, email, and workspace configuration. Integrations and Context (uploaded documents) live here too."
      tips={[
       'Changes to workspace settings affect all members.',
       'API keys and billing are per-workspace, not per-user.',
      ]}
     />
    )}
   </section>

   {/* Body: sidebar + content */}
   <div className="flex gap-6 md:gap-8">

    {/* Mobile horizontal nav (only sub-pages, not the index) */}
    {!isIndex && (
     <nav className="lg:hidden -mx-2 px-2 overflow-x-auto mb-4 absolute left-0 right-0 top-0 hidden">
      {/* placeholder — mobile gets the full-width segmented bar
          rendered just below the header outside this layout flex */}
     </nav>
    )}

    {/* Desktop vertical nav */}
    <nav className="w-52 shrink-0 hidden lg:block">
     <ul className="flex flex-col gap-0.5">
      {SECTIONS.map((s) => {
       const isActive = active?.href === s.href;
       return (
        <li key={s.href}>
         <Link
          href={s.href}
          className={cn(
           'flex items-center gap-2 px-3 h-8 rounded-md text-[12.5px] transition-colors',
           isActive
            ? 'bg-[color:var(--ink)] text-[color:var(--paper)] font-medium'
            : 'text-[color:var(--ink-2)] hover:text-[color:var(--ink)] hover:bg-[color:var(--paper-2)]',
          )}
         >
          {s.label}
         </Link>
        </li>
       );
      })}
     </ul>
    </nav>

    {/* Main content — mobile gets a horizontal nav strip above */}
    <div className="flex-1 min-w-0">
     {/* Mobile-only horizontal scrollable nav. We render it here
         (inside the content column) so it appears above the
         active sub-page's content on small screens. */}
     <nav className="lg:hidden -mx-2 mb-4 overflow-x-auto">
      <ul className="flex items-center gap-1 px-2 pb-1 min-w-max">
       {SECTIONS.map((s) => {
        const isActive = active?.href === s.href;
        return (
         <li key={s.href} className="shrink-0">
          <Link
           href={s.href}
           className={cn(
            'inline-flex items-center h-7 px-3 rounded-md text-[12px] transition-colors',
            isActive
             ? 'bg-[color:var(--ink)] text-[color:var(--paper)] font-medium'
             : 'text-[color:var(--ink-2)] border border-[color:var(--rule)] bg-[color:var(--paper)] hover:border-[color:var(--ink-3)]',
           )}
          >
           {s.label}
          </Link>
         </li>
        );
       })}
      </ul>
     </nav>

     {children}
    </div>
   </div>
  </div>
 );
}
