'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { motion } from 'framer-motion';
import { cn } from '@/lib/utils';
import { PageHelp } from '@/components/ui/PageHelp';

/* ─────────────────────────────────────────────────────────────────
 * Settings shell — header + left-sidebar nav + content slot.
 *
 * Each sub-route renders its own content; the layout provides:
 *  - a page header bar (title + breadcrumb)
 *  - a left sidebar with all settings sections
 *  - the content frame (right)
 *
 * Active state is driven by the current pathname. Mobile collapses
 * the sidebar into a horizontal scrollable chip list.
 * ───────────────────────────────────────────────────────────────── */

const SECTIONS: Array<{ href: string; label: string; lede: string; helpBody: string; helpTips?: string[] }> = [
 {
  href: '/dashboard/settings/account',
  label: 'Account',
  lede: 'Your profile, password, and session.',
  helpBody: 'Personal account settings — your display name, email address, and password. Changes here apply only to your user account, not the workspace.',
  helpTips: ['Your name appears on outreach drafts generated by the AI.', 'Password changes take effect immediately and sign out other sessions.'],
 },
 {
  href: '/dashboard/settings/workspace',
  label: 'Workspace',
  lede: 'The desk name, defaults, and preferences.',
  helpBody: 'Workspace-level settings shared by all members — name, notification preferences, and export defaults.',
  helpTips: ['Renaming the workspace updates it for all members.', 'These settings affect every search and campaign in this workspace.'],
 },
 {
  href: '/dashboard/settings/team',
  label: 'Team',
  lede: 'Members, roles, and invitations.',
  helpBody: 'View everyone who has access to this workspace. Invite new members by email to collaborate on searches and campaigns.',
  helpTips: ['Each member can run searches and view leads by default.', 'Admin members can manage billing and workspace settings.'],
 },
 {
  href: '/dashboard/settings/knowledge-base',
  label: 'Knowledge base',
  lede: 'House style — what the agent should know about your company.',
  helpBody: 'Custom knowledge the AI uses when writing emails or qualifying leads. Add your company overview, value proposition, and ideal customer profile.',
  helpTips: ['More specific context produces more targeted outreach.', 'The AI quotes this knowledge when generating email drafts.'],
 },
 {
  href: '/dashboard/settings/data-sources',
  label: 'Data sources',
  lede: 'Connected providers and their credentials.',
  helpBody: 'Configure which data sources the AI uses during prospecting — built-in sources, your own Apollo API key, and custom uploads.',
  helpTips: ['Enable or disable sources to control cost and data freshness.', 'View per-source usage and invocation counts.'],
 },
 {
  href: '/dashboard/settings/suppression',
  label: 'Suppression list',
  lede: 'Emails and domains the engine must never contact.',
  helpBody: 'Email addresses and domains that will never appear in search results or receive campaign emails. Use this for unsubscribers, competitors, and existing customers.',
  helpTips: ['Add full domains (e.g. competitor.com) to suppress all contacts there.', 'Suppressed contacts are filtered automatically from every search.'],
 },
 {
  href: '/dashboard/settings/api-keys',
  label: 'API keys',
  lede: 'Credentials for programmatic access.',
  helpBody: 'Generate API keys to access LeadreAI programmatically. Keys are shown once — copy and store them securely. Revoke any key at any time.',
  helpTips: ['Each key has a name to help you identify which service is using it.', 'Keys inherit the permissions of the workspace they belong to.'],
 },
 {
  href: '/dashboard/settings/billing',
  label: 'Billing & usage',
  lede: 'Plan, credits, and the ledger.',
  helpBody: 'Manage your subscription plan and credit balance. Monthly plan credits refill each billing cycle; top-up credits stack on top and never expire.',
  helpTips: ['One credit = one search job, regardless of lead count returned.', 'Top-ups are one-off purchases via Stripe or Paystack.'],
 },
 {
  href: '/dashboard/settings/email',
  label: 'Email & replies',
  lede: 'Sending account and inbound reply routing.',
  helpBody: 'Configure the email account used for outreach. Connect Gmail OAuth for branded sending, or set up custom SMTP, Resend, or SendGrid. Inbound webhooks route replies back to the campaign dashboard.',
  helpTips: ['Gmail OAuth is the simplest setup — no SMTP credentials required.', 'Inbound routing lets you see replies directly in each campaign.'],
 },
];

export default function SettingsLayout({ children }: { children: React.ReactNode }) {
 const pathname = usePathname();
 const isIndex = pathname === '/dashboard/settings';
 const active = SECTIONS.find((s) => pathname === s.href || pathname.startsWith(s.href + '/'));

 return (
  <motion.div
   initial={{ opacity: 0, y: 10 }}
   animate={{ opacity: 1, y: 0 }}
   transition={{ duration: 0.28 }}
  >
   {/* Settings header */}
   <div className="bg-[color:var(--paper)] border-b border-[color:var(--rule)] px-8 py-6">
    <div className="max-w-4xl mx-auto flex items-start justify-between gap-4">
     <div>
      <h1 className="text-[24px] font-bold tracking-tight text-[color:var(--ink)]">Settings</h1>
      <p className="text-[13.5px] text-[color:var(--ink-3)] mt-0.5">
       {isIndex
        ? 'Manage your workspace, team, integrations, and billing.'
        : (active?.lede ?? 'Manage your workspace.')}
      </p>
     </div>
     {active && (
      <PageHelp
       title={active.label}
       body={active.helpBody}
       tips={active.helpTips}
      />
     )}
     {isIndex && (
      <PageHelp
       title="Settings"
       body="Central settings hub. Navigate to account, billing, team, email, and workspace configuration. Integrations (HubSpot, webhooks, email) are on the Integrations page."
       tips={[
        'Changes to workspace settings affect all members.',
        'API keys and billing are per-workspace, not per-user.',
       ]}
      />
     )}
    </div>
   </div>

   {/* Body: sidebar + content */}
   <div className="max-w-4xl mx-auto px-8 py-6 flex gap-6">

    {/* Left sidebar nav */}
    <nav className="w-48 shrink-0">
     {/* Mobile: horizontal scroll */}
     <div className="lg:hidden -mx-2 px-2 overflow-x-auto mb-4">
      <div className="flex items-center gap-2 pb-3 min-w-max">
       {SECTIONS.map((s) => {
        const isActive = active?.href === s.href;
        return (
         <Link
          key={s.href}
          href={s.href}
          className={cn(
           'inline-flex items-center px-3 py-1.5 rounded-full border text-[12px] font-medium transition-colors whitespace-nowrap',
           isActive
            ? 'bg-[color:var(--forest)] text-white border-[color:var(--forest)]'
            : 'border-[color:var(--rule)] text-[color:var(--ink-2)] hover:text-[color:var(--ink)]',
          )}
         >
          {s.label}
         </Link>
        );
       })}
      </div>
     </div>

     {/* Desktop: vertical list */}
     <ul className="hidden lg:flex flex-col gap-0.5">
      {SECTIONS.map((s) => {
       const isActive = active?.href === s.href;
       return (
        <li key={s.href}>
         <Link
          href={s.href}
          className={cn(
           'flex items-center gap-2 px-3 py-2 rounded-lg text-[13px] font-medium transition-colors',
           isActive
            ? 'bg-[color:var(--forest)]/10 text-[color:var(--forest)]'
            : 'text-[color:var(--ink-2)] hover:bg-[color:var(--paper-3)] hover:text-[color:var(--ink)]',
          )}
         >
          {isActive && (
           <span className="w-1 h-1 rounded-full bg-[color:var(--forest)] shrink-0" />
          )}
          <span className={isActive ? '' : 'ml-3'}>{s.label}</span>
         </Link>
        </li>
       );
      })}
     </ul>
    </nav>

    {/* Main content */}
    <div className="flex-1 min-w-0">{children}</div>
   </div>
  </motion.div>
 );
}
